load("@rules_python//python:defs.bzl", "py_library")

py_library(
  name = "preprocessing",
  srcs = glob(["*.py"]),
  visibility = ["//visibility:public"],
  deps = ["//protos/sample:sample_py_protos"]
)
